name: Laravel Test

on:
  push:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql, xml

      - name: Copy .env.ci to .env.testing
        run: cp .env.ci .env.testing

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Generate application key
        run: php artisan key:generate --env=testing

      - name: Run database migrations
        run: php artisan migrate --env=testing --force

      - name: Run Laravel tests
        run: php artisan test --env=testing
